version: "3.9"
services:
  postgres:
    image: postgresql_test
    container_name: postgres-test
    build:
      context: .
      dockerfile: build/docker/psql/Dockerfile
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgresql"
    volumes:
      - ./build/docker/psql/data:/var/lib/postgresql/data
      - ./build/docker/psql/config/.walg.json:/var/lib/postgresql/.walg.json
      - ./build/docker/psql/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./app:/app
    ports:
      - "9023:9023"
  mariadb:
    image: mariadb-test
    container_name: mariadb-test
    build:
      context: .
      dockerfile: build/docker/mariadb/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./build/docker/mariadb/data:/var/lib/mysql
      - ./build/docker/mariadb/config/.walg.json:/var/lib/mysql/.walg.json
      - ./build/docker/mariadb/config/.my.cnf:/var/lib/mysql/.my.cnf
      - ./app:/app
  mysql:
    image: mysql-test
    container_name: mysql-test
    build:
      context: .
      dockerfile: build/docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./build/docker/mysql/data:/var/lib/mysql
      - ./build/docker/mysql/config/.walg.json:/var/lib/mysql/.walg.json
      - ./build/docker/mysql/config/.my.cnf:/var/lib/mysql/.my.cnf
      - ./app:/app
  mongo:
    image: mongo-test
    container_name: mongo-test
    build:
      context: .
      dockerfile: build/docker/mongo/Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./build/docker/mongo/data:/data/db
      - ./build/docker/mongo/config/.walg.json:/data/db/.walg.json
      - ./app:/app
  clickhouse:
    image: clickhouse-test
    container_name: clickhouse-test
    build:
      context: .
      dockerfile: build/docker/clickhouse/Dockerfile
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_DB=clickhouse
    volumes:
      - ./build/docker/clickhouse/data:/var/lib/clickhouse
      - ./build/docker/clickhouse/config/config.yml:/etc/clickhouse-backup/config.yml
      - ./build/docker/clickhouse/init-scripts:/docker-entrypoint-initdb.d
      - ./app:/app
